[build]
builder = "NIXPACKS"

[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["cd backend && npm install"]

[phases.build]
cmds = ["cd backend && npm run build"]

[start]
cmd = "cd backend && npm start"



buildCommand = "npm install && npm run build"
startCommand = "npm start"
root = "backend"

[env]
PORT = "4000"
